php:
  preset: laravel
  disabled:
    - unused_use
  finder:
    not-name:
      - index.php
      - server.php
    exclude:
      - node_modules
      - storage
      - vendor
#js:
#  finder:
#    not-name:
#      - webpack.mix.js
#css: true
